# Generated by Django 4.0.4 on 2022-05-13 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainlk', '0002_alter_student_options_alter_teacher_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='education',
            field=models.CharField(blank=True, max_length=50, verbose_name='Образование'),
        ),
        migrations.AddField(
            model_name='teacher',
            name='photo',
            field=models.ImageField(blank=True, upload_to='teachers_photos/', verbose_name='Фотография'),
        ),
    ]
