# Generated by Django 4.0.4 on 2022-05-13 12:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainlk', '0003_teacher_education_teacher_photo'),
    ]

    operations = [
        migrations.CreateModel(
            name='SchoolSubjectForList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, verbose_name='Наименование предмета')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainlk.teacher', verbose_name='Учитель')),
            ],
            options={
                'verbose_name': 'Школьный предмет',
                'verbose_name_plural': 'Школьные предметы',
            },
        ),
    ]
