# Generated by Django 4.0.4 on 2022-04-28 11:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('mainlk', '0002_alter_student_options_alter_teacher_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MaterialForStudy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Наименование раздела')),
            ],
            options={
                'verbose_name': 'Раздел материала',
                'verbose_name_plural': 'Разделы материала',
            },
        ),
        migrations.CreateModel(
            name='MethodicalMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Наименование раздела')),
            ],
            options={
                'verbose_name': 'Раздел методического материала',
                'verbose_name_plural': 'Разделы методического материала',
            },
        ),
        migrations.CreateModel(
            name='SchoolSubject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, verbose_name='Наименование предмета')),
                ('subject_class', models.PositiveSmallIntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9)], verbose_name='Класс предмета')),
            ],
            options={
                'verbose_name': 'Школьный предмет',
                'verbose_name_plural': 'Школьные предметы',
                'ordering': ('subject_class',),
            },
        ),
        migrations.CreateModel(
            name='ThemesMethodicalMaterials',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Наменование темы')),
                ('slug', models.SlugField(max_length=100, verbose_name='Слаг темы')),
                ('text', models.TextField(verbose_name='Текст темы')),
                ('material_for_study', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='materialslk.methodicalmaterial', verbose_name='Раздел методического материала')),
            ],
            options={
                'verbose_name': 'Тема раздела для методического материала',
                'verbose_name_plural': 'Темы раздела для методического материала',
            },
        ),
        migrations.CreateModel(
            name='ThemesMaterialsForStudy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Наменование темы')),
                ('slug', models.SlugField(max_length=100, verbose_name='Слаг темы')),
                ('text', models.TextField(verbose_name='Текст темы')),
                ('material_for_study', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='materialslk.materialforstudy', verbose_name='Раздел материала')),
            ],
            options={
                'verbose_name': 'Тема раздела',
                'verbose_name_plural': 'Темы раздела',
            },
        ),
        migrations.CreateModel(
            name='StudentAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='students_files/%Y/%m/%d/', verbose_name='Файл ответа студента')),
                ('comment', models.TextField(max_length=200, verbose_name='Комментарий ответа студента')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainlk.student', verbose_name='Ученик')),
                ('theme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='materialslk.themesmaterialsforstudy', verbose_name='Тема')),
            ],
        ),
        migrations.AddField(
            model_name='methodicalmaterial',
            name='school_subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='materialslk.schoolsubject', verbose_name='Школьный предмет'),
        ),
        migrations.AddField(
            model_name='methodicalmaterial',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainlk.teacher', verbose_name='Учитель'),
        ),
        migrations.AddField(
            model_name='materialforstudy',
            name='school_subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='materialslk.schoolsubject', verbose_name='Школьный предмет'),
        ),
        migrations.AddField(
            model_name='materialforstudy',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainlk.teacher', verbose_name='Учитель'),
        ),
        migrations.CreateModel(
            name='FileTheme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='materials_files/%Y/%m/%d/', verbose_name='Файл темы')),
                ('theme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='materialslk.themesmaterialsforstudy', verbose_name='Тема')),
            ],
            options={
                'verbose_name': 'Файл темы',
                'verbose_name_plural': 'Файлы темы',
            },
        ),
        migrations.CreateModel(
            name='FileMethodicalTheme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='materials_files/%Y/%m/%d/', verbose_name='Файл темы')),
                ('theme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='materialslk.themesmaterialsforstudy', verbose_name='Тема')),
            ],
            options={
                'verbose_name': 'Файл темы для методического материала',
                'verbose_name_plural': 'Файлы темы для методического материала',
            },
        ),
    ]
