# Generated by Django 4.0.2 on 2022-04-28 12:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainlk', '0002_alter_student_options_alter_teacher_options_and_more'),
        ('materialslk', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='filemethodicaltheme',
            options={'verbose_name': 'Файл (Методические материалы)', 'verbose_name_plural': 'Файлы (Методические материалы)'},
        ),
        migrations.AlterModelOptions(
            name='filetheme',
            options={'verbose_name': 'Файл (Материалы для обучения)', 'verbose_name_plural': 'Файлы (Материалы для обучения)'},
        ),
        migrations.AlterModelOptions(
            name='materialforstudy',
            options={'verbose_name': 'Раздел (Материалы для обучения)', 'verbose_name_plural': 'Разделы (Материалы для обучения)'},
        ),
        migrations.AlterModelOptions(
            name='methodicalmaterial',
            options={'verbose_name': 'Раздел (Методические материалы)', 'verbose_name_plural': 'Разделы (Методические материалы)'},
        ),
        migrations.AlterModelOptions(
            name='studentanswer',
            options={'verbose_name': 'Ответ студента (Материалы для обучения)', 'verbose_name_plural': 'Ответы студентов (Материалы для обучения)'},
        ),
        migrations.AlterModelOptions(
            name='themesmaterialsforstudy',
            options={'verbose_name': 'Тема (Материалы для обучения)', 'verbose_name_plural': 'Темы (Материалы для обучения)'},
        ),
        migrations.AlterModelOptions(
            name='themesmethodicalmaterials',
            options={'verbose_name': 'Тема (Методические материалы)', 'verbose_name_plural': 'Темы (Методические материалы)'},
        ),
        migrations.RemoveField(
            model_name='materialforstudy',
            name='teacher',
        ),
        migrations.RemoveField(
            model_name='methodicalmaterial',
            name='teacher',
        ),
        migrations.AddField(
            model_name='schoolsubject',
            name='teacher',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='mainlk.teacher', verbose_name='Учитель'),
        ),
    ]
