# Generated by Django 4.0.2 on 2022-05-09 09:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainlk', '0002_alter_student_options_alter_teacher_options_and_more'),
        ('materialslk', '0002_alter_filemethodicaltheme_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentanswer',
            name='comment',
        ),
        migrations.AlterField(
            model_name='schoolsubject',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainlk.teacher', verbose_name='Учитель'),
        ),
    ]
