# Generated by Django 4.0.4 on 2022-05-11 09:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('materialslk', '0003_remove_studentanswer_comment_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filemethodicaltheme',
            name='theme',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='materialslk.themesmethodicalmaterials', verbose_name='Тема'),
        ),
        migrations.AlterField(
            model_name='materialforstudy',
            name='school_subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='materialslk.schoolsubject', verbose_name='Школьный предмет'),
        ),
        migrations.AlterField(
            model_name='methodicalmaterial',
            name='school_subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='materialslk.schoolsubject', verbose_name='Школьный предмет'),
        ),
        migrations.AlterField(
            model_name='themesmaterialsforstudy',
            name='material_for_study',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='materialslk.materialforstudy', verbose_name='Раздел материала'),
        ),
        migrations.AlterField(
            model_name='themesmethodicalmaterials',
            name='material_for_study',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='materialslk.methodicalmaterial', verbose_name='Раздел методического материала'),
        ),
    ]
