# Generated by Django 4.0.4 on 2022-05-11 20:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainlk', '0002_alter_student_options_alter_teacher_options_and_more'),
        ('materialslk', '0004_alter_filemethodicaltheme_theme_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FavouritesMethodical',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='materialslk.themesmethodicalmaterials', verbose_name='Ссылка на материал')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainlk.student', verbose_name='Студент')),
            ],
        ),
        migrations.CreateModel(
            name='FavouritesForStudy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='materialslk.themesmaterialsforstudy', verbose_name='Ссылка на материал')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainlk.student', verbose_name='Студент')),
            ],
        ),
    ]
