# Generated by Django 4.0.4 on 2022-05-11 22:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('materialslk', '0005_favouritesmethodical_favouritesforstudy'),
    ]

    operations = [
        migrations.RenameField(
            model_name='themesmethodicalmaterials',
            old_name='material_for_study',
            new_name='material_methodical',
        ),
    ]
