# Generated by Django 4.0.4 on 2022-05-13 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materialslk', '0006_rename_material_for_study_themesmethodicalmaterials_material_methodical'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='favouritesforstudy',
            options={'verbose_name': 'Избранное (Материалы для обучения)', 'verbose_name_plural': 'Избранные (Материалы для обучения)'},
        ),
        migrations.AlterModelOptions(
            name='favouritesmethodical',
            options={'verbose_name': 'Избранное (Методические материалы)', 'verbose_name_plural': 'Избранные (Методические материалы)'},
        ),
        migrations.AddConstraint(
            model_name='favouritesforstudy',
            constraint=models.UniqueConstraint(fields=('student', 'material'), name='unique_student_material_for_study'),
        ),
        migrations.AddConstraint(
            model_name='favouritesmethodical',
            constraint=models.UniqueConstraint(fields=('student', 'material'), name='unique_student_material_methodical'),
        ),
    ]
